version: "3.7"
services:
  bot1:
    container_name: bot1
    tty: true
    build:
      context: .
    restart: unless-stopped
    cap_add:
      # Google Chrome
      - SYS_ADMIN
    environment:
      - VNC_PASSWORD=123mudar
      - HTTP_PASSWORD=123mudar
      - TZ=America/Sao_Paulo
      - RESOLUTION=1024x768
      - USER=ubuntu
    volumes:
       - /dev/shm:/dev/shm
       - bot1_data:/home/ubuntu/
    ports:
      - 5900:5900
volumes:
    bot1_data:

