version: "3.7"
services:
  bot1:
    container_name: bot1
    tty: true
    build:
      context: .
      #shm_size: '2g'
    #shm_size: '2g'
    restart: unless-stopped
    cap_add:
      # Google Chrome
      - SYS_ADMIN
    environment:
      - VNC_PASSWORD=123mudar
      - HTTP_PASSWORD=123mudar
      - TZ=America/Sao_Paulo
      - RESOLUTION=1920x1080
      - USER=ubuntu
    volumes:
       - /dev/shm:/dev/shm
       - bot1_data:/home/ubuntu/
    ports:
      - 5900:5900
      - 6080:80
    deploy:
      resources:
        limits:
          memory: 3096M
          cpus: '1.2'
        reservations:
          memory: 2048M
          cpus: '1'
  bot2:
    container_name: bot2
    tty: true
    build:
      context: .
      shm_size: '2g'
    shm_size: '2g'
    restart: unless-stopped
    cap_add:
      # Google Chrome / brave
      - SYS_ADMIN
    environment:
      - VNC_PASSWORD=123mudar
      - HTTP_PASSWORD=123mudar
      - TZ=America/Sao_Paulo
      - RESOLUTION=1920x1080
      - USER=ubuntu
    volumes:
       - /dev/shm:/dev/shm
       - bot2_data:/home/ubuntu/
    ports:
      - 5901:5900
      - 6081:80
    deploy:
      resources:
        limits:
          memory: 3096M
          cpus: '1.2'
        reservations:
          memory: 2048M
          cpus: '1'

volumes:
    bot1_data:
    bot2_data:
